### ISSUE TITLE
HTTP Basic Auth

### ISSUE THREAD

**Issue by vanboom** [rubiii/savon#3]
Hi, 
Something has broken with my latest update to Savon 2.1.0.  I am getting HTTP error (401): Unauthorized Request. Bad or missing credentials.

I am attempting HTTP Basic Auth using...

client = Savon::client(:wsdl=>@wsdl, :basic_auth=>[@http_auth_user, @http_auth_password])

All parameters are correct.  Could you please help with a clear example of how to enable HTTP Basic Auth?  

Maybe we have a bug somewhere else in httpi gem or wasabi gem? 

Old Working Config: 
savon 1.2.0
httpi  1.1.1
wasabi 2.5.1

New Failing Config:
savon 2.1.0
httpi 2.0.2
wasabi 3.0.0

I have tested the HTTP credentials with SoapUI and they are correct.  Something seems to be broken with Savon not doing the HTTP Basic Auth.

Thanks,
Don

**Comment by rubiii** [comment]
the repo has been moved. could you please [create a new issue here](https://github.com/savonrb/savon/issues)? thanks!
